config/routes.rb
Rails.application.routes.draw do
  root 'top_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :name, presence: true
  validates :password, confirmation: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController

  def top; end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new;end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, notice: 'ログインしました'
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'ユーザー登録が完了しました'
    else
      flash.now[:alert] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamDevelopment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= yield %>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-base-200 text-base-content rounded">
  <div class="grid grid-flow-col gap-4">
    <a class="link link-hover">お問い合わせ</a>
    <a class="link link-hover">利用規約</a>
    <a class="link link-hover">プライバシーポリシー</a>
    <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a>
  </div>
  <div>
    <p>Copyright © 2023 - All rights reserved by Team Development.</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="body-font">
  <div class="navbar bg-primary text-white">
    <div class="flex-1 px-2 lg:flex-none">
      <a class="text-lg font-bold">daisyUI</a>
    </div>
    <div class="flex justify-end flex-1 px-2">
      <div class="flex items-stretch">
        <a class="btn btn-ghost rounded-btn">Button</a>
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost rounded-btn">Dropdown</label>
        <ul tabindex="0" class="text-gray-700 menu dropdown-content z-[1] p-2 shadow bg-base-100 bg- rounded-box w-52 mt-4">
            <li><a>Item 1</a></li>
            <li><a>Item 2</a></li>
            <li><%= button_to t('defaults.logout'), '#', method: :delete %></li>
          </ul>
        </label>
      </div>
    <%# else %>
      <%= link_to t('defaults.login'), '#', class: 'btn btn-square btn-ghost whitespace-nowrap w-24' %>
    <%# end %>
  </div>
</header>

app/views/top_pages/top.html.erb
<div class='top-wrapper px-20'>
  <div class='my-20 text-center'>
    <h1 class="text-3xl font-bold underline">
        Hello world!
    </h1>

    <button class="bg-gray-900 hover:bg-gray-800 text-white rounded px-4 py-2">tailwind</button>

    <button class="btn">daisyUI</button>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ログイン</h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit 'ログイン', class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to '登録ページへ', new_user_path %>
        <a href="#">パスワードをお忘れの方はこちら</a>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div
  class="block max-w-md rounded-lg bg-white p-6 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] dark:bg-neutral-700">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div input type="text" placeholder="Type here" class="input input-bordered input-secondary w-full max-w-xs" >
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div input type="text" placeholder="Type here" class="input input-bordered input-secondary w-full max-w-xs" >
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div input type="text" placeholder="Type here" class="input input-bordered input-secondary w-full max-w-xs" >
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div input type="text" placeholder="Type here" class="input input-bordered input-secondary w-full max-w-xs" >
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>